INSERT INTO ACCOUNT (PASS,NAME,QTYPE,FOOD,STORE,COMENT)
VALUES('1111','A','うどん・そば','きつねうどん','XX製麺','うどん好きです！');
INSERT INTO ACCOUNT (PASS,NAME,QTYPE,FOOD,STORE,COMENT)
VALUES('2222','B','カレー','カツカレー','AAカレー屋','カツカレー最高!');
INSERT INTO ACCOUNT (PASS,NAME,QTYPE,FOOD,STORE,COMENT)
VALUES('3333','C','ラーメン','味噌ラーメン','GGラーメン','ラーメンを食べ歩きたい');

INSERT INTO MUTTER (NAME,QTYPE,STORE,MEMO,STAR,TIME,USER_ID)
VALUES('A','うどん・そば','うどん屋BB','きつねうどんがうまい','★4','2024/1/13 12:48',1);
INSERT INTO MUTTER (NAME,QTYPE,STORE,MEMO,STAR,TIME,USER_ID)
VALUES('B','カレー','ZZ満腹カレー','カレーの大盛が食べ応えあり','★3','2024/1/14 11:34',2);
INSERT INTO MUTTER (NAME,QTYPE,STORE,MEMO,STAR,TIME,USER_ID)
VALUES('B','カレー','MMカレー堂','日替わりカレーが良い','★3','2024/1/14 15:05',2);
INSERT INTO MUTTER (NAME,QTYPE,STORE,MEMO,STAR,TIME,USER_ID)
VALUES('C','ラーメン','味噌ラーメンGG','味噌の味わいが深い','★4','2024/1/14 12:45',3);
INSERT INTO MUTTER (NAME,QTYPE,STORE,MEMO,STAR,TIME,USER_ID)
VALUES('C','ラーメン','豚骨ラーメンMM','大盛で食べ応えあり','★4','2024/1/14 12:45',3);