create database tabettar;

CREATE TABLE ACCOUNT (
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
PASS VARCHAR(10) NOT NULL,
NAME VARCHAR(40) NOT NULL,
QTYPE VARCHAR(10) DEFAULT ' ' NOT NULL,
FOOD VARCHAR(100) DEFAULT ' ' NOT NULL,
STORE VARCHAR(100) DEFAULT ' ' NOT NULL,
COMENT VARCHAR(255) DEFAULT ' ' NOT NULL
);

CREATE TABLE MUTTER (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
QTYPE VARCHAR(10) NOT NULL,
STORE VARCHAR(100) NOT NULL,
MEMO VARCHAR(255) NOT NULL,
STAR CHAR(10) NOT NULL,
TIME VARCHAR(100) NOT NULL,
USER_ID INT NOT NULL
);